# -*- coding: utf-8 -*-
"""Data Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRzvRbxVt8t9g2NGiJpPbgSfwar7kg-h
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3])
y = np.array([2,35,5,27])
plt.scatter (x,y)
plt.plot(x,y,'-', c="black", marker=".", ms="15", mec="blue",mfc="skyblue")
plt.title('Speed-Time Graph', fontsize=14)
plt.xlabel("Time --->")
plt.ylabel("speed --->")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([3,2,4,1,8])
y = np.array([9,100,20,30,20])
plt.subplot(2,2,1)
plt.plot(x,y,c="red")
plt.subplot(2,2,2)
plt.plot(x,y,c="black")
plt.subplot(2,2,3)
plt.plot(x,y,c="blue")
plt.subplot(2,2,4)
plt.plot(x,y,c="green")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array(["2 PM","5 PM","7 PM","9 PM"])
y = np.array([12,35,27,9])
plt.title('Sales Trend', fontsize=14)
plt.xlabel("Time --->")
plt.ylabel("Product Sold --->")
plt.bar (x[0],y[0], color="pink")
plt.bar (x[1],y[1], color="lightgreen")
plt.bar (x[2],y[2], color="yellow")
plt.bar (x[3],y[3], color="skyblue")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([25, 5, 45, 20, 5])
myexplode = np.array([0.5, 0.3, 0.4, 0.3, 0.2])
mylabels = np.array(["TV", "Laptop", "Smart Phone", "Headphone", "Watch"])
mycolors = np.array(["yellow", "orange", "pink", "skyblue", "lightgreen"])
plt.figure(figsize=(8, 6))
plt.pie(x, labels=mylabels, colors=mycolors, startangle=90)
plt.title('Product Distribution', fontsize=14)
plt.legend(mylabels, title="Products", loc="best", bbox_to_anchor=(1, 0.5))
plt.axis('equal')
plt.show()

from google.colab import files # to import the files from the system
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("posts.csv")

x = df ['Post_Type'].values
y = df ['likes'].values
plt.scatter(x,y,color='lightgreen')
plt.xlabel('Post Type -->')
plt.ylabel('Likes -->')
plt.title('Linear Regression')
df.describe
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import numpy as np

le = LabelEncoder()
x_encoded = le.fit_transform(x.ravel()).reshape(-1, 1)
reg = LinearRegression()
reg.fit(x_encoded, y)

# Predict
y_pred = reg.predict(x_encoded)

print("Predictions:", y_pred)
print("Slope:", reg.coef_)
print("Intercept:", reg.intercept_)

import matplotlib.pyplot as plt
import numpy as np
x_flat = x.flatten()
y_flat = y.flatten() if y.ndim > 1 else y
plt.scatter(x_flat, y_flat, color='red', label='Data Points')
sorted_indices = np.argsort(x_flat)
plt.plot(x_flat[sorted_indices], y_pred[sorted_indices], color='grey', label='Regression Line')

# Add labels and legend
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Linear Regression')
plt.legend()

# Show plot
plt.show()